### ISSUE TITLE
Some Parts Not Available for Given Link

### ISSUE THREAD

**Issue by philipbl** [caedm/wall-ink#11]
Two items in the part list can no longer be found using the provided links:

Micro JST PH 2.0 2Pin Right-Angle Socket Male and Connector Female w./ wire
https://www.ebay.com/itm/202013987748

JST_PH 2.0mm Pitch 8-pin double end female cable
https://www.ebay.com/itm/192369804646

It would be great if we could get a new link with an equivalent part.

Thanks!

**Comment by jdeananderson** [comment]
I have updated the links.  Thanks.

**Comment by philipbl** [comment]
Thanks!
