### ISSUE TITLE
wall-ink in different timezone

### ISSUE THREAD

**Issue by zhongshanliyu** [caedm/wall-ink#22]
I just figure out the wall-server doesn't support multiple timezones in a single Linux server.  all images are generation timestamp from the server.

**Comment by zhongshanliyu** [comment]
![image](https://user-images.githubusercontent.com/54261373/66612624-37202580-eb77-11e9-8bab-e6b5e3e8c268.png)

**Comment by AndersenJ** [comment]
Sorry, we have no plans to support this. If you need to support multiple physical locations in multiple timezones, I recommend spinning up more than one instance of wall-ink-server on the same server.

Best of luck!
