### ISSUE TITLE
Devices for sell

### ISSUE THREAD

**Issue by al-indigo** [caedm/wall-ink#23]
I'm dumb at electronics but I really want to have 10 devices for https://www.ispras.ru/en/ .

Do you have an option to sell me spare devices or to make them for some money with shipping to Moscow? If you do, what could be the cost? I suppose the case we would print ourselves, but the main part could take a lot of time.

**Comment by AndersenJ** [comment]
Sorry about this, but after some internal discussion we decided we aren't able to do this for you. I'm sure you could find someone local who could help you with it though!
