### ISSUE TITLE
Delay functions issue

### ISSUE THREAD

**Issue by patryk-kawalarz** [caedm/wall-ink#31]
You wrote in docs:

_For some stupid reason, the delay() and yield() commands crash the ESP8266 unless they are called directly from within loop() or setup() [...]. This has encouraged me to write code in a worse way._

But there's an alternative for ```delay()``` function. You can do the same using ```while``` loop:
```c++
while(millis() < time_now + period){}
```

**Comment by AndersenJ** [comment]
That is not at all the same thing. The primary reason to run delay() or yield() would be to pass execution back to the operating system so it can manage the wifi and feed the watchdog. the code snippet you posted is just a busy loop, which doesn't have any purpose except to take up time and drain the batteries.
